apiVersion: v1
kind: Service
metadata:
    name: demo-e2e
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: demo-e2e

---

apiVersion : apps/v1
kind: Deployment
metadata:
  name: demo-e2e 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-e2e 
    spec:
      containers:
        - name: demo-e2e 
          image: dsmsacr.azurecr.io/demo-e2e
          ports:
          - containerPort: 80
